/*
 * transmission.h
 *
 *  Created on: ??þ/??þ/????
 *      Author: ASHRY
 */

#ifndef PERCEPTION_COMMUNICATION_TRANSMISSION_TRANSMISSION_H_
#define PERCEPTION_COMMUNICATION_TRANSMISSION_TRANSMISSION_H_

#define TRANSMISSION_PERIPHERAL 			SPI2
void transmissionVidSendSensorData(sensorTypeDef*);

#endif /* PERCEPTION_COMMUNICATION_TRANSMISSION_TRANSMISSION_H_ */
