/*
 * reception.h
 *
 *  Created on: ??þ/??þ/????
 *      Author: ASHRY
 */

#ifndef ACTUATING_COMMUNICATION_RECEPTION_RECEPTION_H_
#define ACTUATING_COMMUNICATION_RECEPTION_RECEPTION_H_



#endif /* ACTUATING_COMMUNICATION_RECEPTION_RECEPTION_H_ */
